### ISSUE TITLE
contribute best practices to bibliometric analytics as r pkg paper

### ISSUE THREAD

**Issue by maxheld83** [subugoe/openairegraph#3]

**Comment by maxheld83** [comment]
this now lives here, will make some additions.

**Comment by njahn82** [comment]
`skg2020_submission` branch tracks the progress

**Comment by maxheld83** [comment]
I'm not sure there's too much to add at this point that would be relevant to *users*; you mention testing and CI, and I'm not sure the technical details would matter much.

I think there *is* going to be something to be said about #7 and related issues with dealing efficiently with the big or expensively computed files that will be useful for users, but that's still a ways off.
So I'm going to close this one here, but feel free to reopen it if you'd like me to write up more on the CI details.

(The CI details will also increasingly be documented in [metaR](https://subugoe.github.io/metaR/reference/index.html) as I factor out stuff there and make it available for everyone -- but here, too, the target audience would be pkg devs, not pkg users).
